version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    image: your-dockerhub-username/ecommerce-app:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ecommerce_php
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
    depends_on:
      - db:
        condition: service_healthy


  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ecommerce_php
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U your_username"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:
  grafana-data: