name: CI

on:
  push:
    branches:
      - main
      - feature/dockercicd
  pull_request:
    branches:
      - main
      - feature/dockercicd

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 
          MYSQL_DATABASE: ecommerce_php
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, pdo, mysql

    - name: Install Dependencies
      run: composer install

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Set Up Test Database
      run: php artisan migrate --env=testing

    - name: Run Tests
      run: php artisan test
