name: Prometheus

on:
  push:
    branches:
      - main
      - feature/dockercicd

global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'laravel_app'
    static_configs:
      - targets: ['localhost:9090']

jobs:
  prometheus:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and Run Docker Image
      run: |
        docker build -t ecommerce:latest .
        docker run -d -p 9090:9090 ecommerce:latest
